name: Tests

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.11']

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --quiet tensorflow tensorflow-probability torch jax jaxlib scikit-learn plotly nbformat ipython pylint coverage pytest matplotlib
          pip install .
          pip list

      - name: Test with pytest
        run: |
          coverage run -m pytest tests/commit

      - name: Upload coverage
        run:
          bash <(curl -s https://codecov.io/bash)

      - name: pylint
        continue-on-error: true
        run: |
          pylint --rcfile=./tests/.pylintrc tests
          pylint --rcfile=./phiml/.pylintrc phiml
